export const DATABASE_ID = "runstats_db";

export const COLLECTIONS = {
  users: "users",
  goals: "goals",
  activities: "activities",
  milestones: "milestones",
  personalRecords: "personal_records",
} as const;

export type CollectionId = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];

export const ATTRS = {
  users: {
    userId: "userId",
    name: "name",
    handle: "handle",
    city: "city",
    avatarFileId: "avatarFileId",
    accentColor: "accentColor",
    stravaAthleteId: "stravaAthleteId",
    stravaAccessToken: "stravaAccessToken",
    stravaRefreshToken: "stravaRefreshToken",
    stravaTokenExpiresAt: "stravaTokenExpiresAt",
    autoSharePR: "autoSharePR",
    autoShareVolume: "autoShareVolume",
    autoShareWeeklyRecap: "autoShareWeeklyRecap",
    onboardingComplete: "onboardingComplete",
    lastSyncAt: "lastSyncAt",
  },
  goals: {
    userId: "userId",
    goalKey: "goalKey",
    name: "name",
    type: "type",
    distanceLabel: "distanceLabel",
    targetValue: "targetValue",
    targetSeconds: "targetSeconds",
    currentValue: "currentValue",
    currentSeconds: "currentSeconds",
    percentage: "percentage",
    done: "done",
    doneAt: "doneAt",
    year: "year",
    isBuiltin: "isBuiltin",
  },
  activities: {
    userId: "userId",
    stravaActivityId: "stravaActivityId",
    title: "title",
    type: "type",
    date: "date",
    distanceMeters: "distanceMeters",
    distanceKm: "distanceKm",
    movingTimeSec: "movingTimeSec",
    elapsedTimeSec: "elapsedTimeSec",
    avgSpeedMps: "avgSpeedMps",
    avgPaceSecPerKm: "avgPaceSecPerKm",
    maxSpeedMps: "maxSpeedMps",
    avgHeartrate: "avgHeartrate",
    maxHeartrate: "maxHeartrate",
    elevationGainM: "elevationGainM",
    calories: "calories",
    summaryPolyline: "summaryPolyline",
    prCount: "prCount",
    achievementCount: "achievementCount",
    bestEfforts: "bestEfforts",
    splitsMetric: "splitsMetric",
    processed: "processed",
  },
  milestones: {
    userId: "userId",
    kind: "kind",
    activityId: "activityId",
    goalId: "goalId",
    pillText: "pillText",
    tone: "tone",
    bigValue: "bigValue",
    bigSub: "bigSub",
    deltaValue: "deltaValue",
    prevValue: "prevValue",
    subtitle: "subtitle",
    date: "date",
    context: "context",
    caption: "caption",
    storyData: "storyData",
    shared: "shared",
    imageFileId: "imageFileId",
    selectedTemplate: "selectedTemplate",
  },
  personalRecords: {
    userId: "userId",
    distanceBucket: "distanceBucket",
    bestTimeSec: "bestTimeSec",
    bestTimeFormatted: "bestTimeFormatted",
    activityId: "activityId",
    achievedAt: "achievedAt",
    previousBestSec: "previousBestSec",
  },
} as const;
